module Fetch
  class API
    def self?.fetch: (
      string,
      ?method: String | Symbol,
      ?headers: _Each[[_ToS, _ToS]],
      ?body: (String | FormData | URLSearchParams)?,
      ?redirect: 'follow' | 'error' | 'manual' | :follow | :error | :manual,
    ) -> Response
  end
end
