module Fetch
  class Client
    include Singleton

    def fetch: (
      string,
      ?method: String | Symbol,
      ?headers: _Each[[_ToS, _ToS]],
      ?body: (String | FormData | URLSearchParams)?,
      ?redirect: 'follow' | 'error' | 'manual' | :follow | :error | :manual,
      ?_redirected: bool
    ) -> Response

    private

    def initialize: () -> void
    def to_response: (string, Net::HTTPResponse, bool) -> Response
  end
end
