module Fetch
  class ConnectionPool
    def initialize: () -> void
    def with_connection: [T] (URI::HTTP) { (Net::HTTP) -> T } -> T

    private

    def checkout: (URI::HTTP) -> Net::HTTP
    def checkin: (URI::HTTP, Net::HTTP) -> void
    def sweep: () -> void
  end
end
