module Fetch
  class FormData
    type value = String | File

    include Enumerable[[String, value]]

    extend Forwardable

    attr_reader entries: Array[[String, value]]

    def self.build: (Enumerable[[Object, Object]]) -> FormData

    def initialize: () -> void
    def append: (Object, Object) -> void
    def delete: (Object) -> void
    def get: (Object) -> value?
    def get_all: (Object) -> Array[value]
    def has: (Object) -> bool
    def keys: -> Array[String]
    def set: (Object, Object) -> void
    def values: () -> Array[value]
    def each: () { ([String, value]) -> void } -> Array[[String, value]]
  end
end
