module Fetch
  class Headers
    include Enumerable[[String, String]]

    def initialize: (_Each[[_ToS, _ToS]]) -> void
    def append: (_ToS, _ToS) -> void
    def delete: (_ToS) -> void
    def entries: () -> Array[[String, String]]
    def get: (_ToS) -> String?
    def has: (_ToS) -> bool
    def keys: -> Array[String]
    def set: (_ToS, _ToS) -> void
    def values: () -> Array[String]

    def each: () { ([String, String]) -> void } -> Array[[String, String]]
            | () -> Enumerator[[String, String], Array[[String, String]]]
  end
end
