name: Test

on:
  push:

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.1.6
          - 3.2.5
          - 3.3.5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake spec
